camera:
- brand: IDS
components:
- stage
- camera
name: Transfer Microscope
objectives:
  Olympus10X:
    magnification: 10
    pixel_to_distance: 0.21709771348256957
  Olympus20X:
    magnification: 20
    pixel_to_distance: 0.10836853687246352
  Olympus4X:
    magnification: 4
    pixel_to_distance: 0.5470330825081491
  Nachet20X-LWD:
    magnification: 20
    pixel_to_distance: 0.1217194985701941
  OlympusSLMPlan50X-LWD:
    magnification: 50
    pixel_to_distance: 0.04397579262355738
stage:
  axes:
    x-axis:
      orientation: 1
      threadpitch: 0.5001931318638403
    y-axis:
      orientation: 1
      threadpitch: 0.5001931318638403
  port: COM10
